// source: farm_ng_proto/tractor/v1/motor.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
goog.exportSymbol('proto.farm_ng_proto.tractor.v1.MotorControllerState', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.farm_ng_proto.tractor.v1.MotorControllerState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.farm_ng_proto.tractor.v1.MotorControllerState.displayName = 'proto.farm_ng_proto.tractor.v1.MotorControllerState';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.toObject = function(opt_includeInstance) {
  return proto.farm_ng_proto.tractor.v1.MotorControllerState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.farm_ng_proto.tractor.v1.MotorControllerState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.toObject = function(includeInstance, msg) {
  var f, obj = {
    rpm: (f = msg.getRpm()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    current: (f = msg.getCurrent()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    dutyCycle: (f = msg.getDutyCycle()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    ampHours: (f = msg.getAmpHours()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    ampHoursCharged: (f = msg.getAmpHoursCharged()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    wattHours: (f = msg.getWattHours()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    wattHoursCharged: (f = msg.getWattHoursCharged()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    tempFet: (f = msg.getTempFet()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    tempMotor: (f = msg.getTempMotor()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    currentIn: (f = msg.getCurrentIn()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    pidPos: (f = msg.getPidPos()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    tachometer: (f = msg.getTachometer()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f),
    inputVoltage: (f = msg.getInputVoltage()) && google_protobuf_wrappers_pb.DoubleValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.farm_ng_proto.tractor.v1.MotorControllerState;
  return proto.farm_ng_proto.tractor.v1.MotorControllerState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.farm_ng_proto.tractor.v1.MotorControllerState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setRpm(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setCurrent(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setDutyCycle(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setAmpHours(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setAmpHoursCharged(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setWattHours(value);
      break;
    case 7:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setWattHoursCharged(value);
      break;
    case 8:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTempFet(value);
      break;
    case 9:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTempMotor(value);
      break;
    case 10:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setCurrentIn(value);
      break;
    case 11:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setPidPos(value);
      break;
    case 12:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setTachometer(value);
      break;
    case 13:
      var value = new google_protobuf_wrappers_pb.DoubleValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.DoubleValue.deserializeBinaryFromReader);
      msg.setInputVoltage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.farm_ng_proto.tractor.v1.MotorControllerState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.farm_ng_proto.tractor.v1.MotorControllerState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRpm();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getCurrent();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getDutyCycle();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getAmpHours();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getAmpHoursCharged();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getWattHours();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getWattHoursCharged();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTempFet();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTempMotor();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getCurrentIn();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getPidPos();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getTachometer();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
  f = message.getInputVoltage();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      google_protobuf_wrappers_pb.DoubleValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.DoubleValue rpm = 1;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.getRpm = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 1));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
*/
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.setRpm = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.clearRpm = function() {
  return this.setRpm(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.hasRpm = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.DoubleValue current = 2;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.getCurrent = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 2));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
*/
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.setCurrent = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.clearCurrent = function() {
  return this.setCurrent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.hasCurrent = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.DoubleValue duty_cycle = 3;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.getDutyCycle = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 3));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
*/
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.setDutyCycle = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.clearDutyCycle = function() {
  return this.setDutyCycle(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.hasDutyCycle = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.DoubleValue amp_hours = 4;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.getAmpHours = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 4));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
*/
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.setAmpHours = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.clearAmpHours = function() {
  return this.setAmpHours(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.hasAmpHours = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.DoubleValue amp_hours_charged = 5;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.getAmpHoursCharged = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 5));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
*/
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.setAmpHoursCharged = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.clearAmpHoursCharged = function() {
  return this.setAmpHoursCharged(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.hasAmpHoursCharged = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.DoubleValue watt_hours = 6;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.getWattHours = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 6));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
*/
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.setWattHours = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.clearWattHours = function() {
  return this.setWattHours(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.hasWattHours = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.DoubleValue watt_hours_charged = 7;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.getWattHoursCharged = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 7));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
*/
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.setWattHoursCharged = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.clearWattHoursCharged = function() {
  return this.setWattHoursCharged(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.hasWattHoursCharged = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.DoubleValue temp_fet = 8;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.getTempFet = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 8));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
*/
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.setTempFet = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.clearTempFet = function() {
  return this.setTempFet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.hasTempFet = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.DoubleValue temp_motor = 9;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.getTempMotor = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 9));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
*/
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.setTempMotor = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.clearTempMotor = function() {
  return this.setTempMotor(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.hasTempMotor = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.DoubleValue current_in = 10;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.getCurrentIn = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 10));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
*/
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.setCurrentIn = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.clearCurrentIn = function() {
  return this.setCurrentIn(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.hasCurrentIn = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional google.protobuf.DoubleValue pid_pos = 11;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.getPidPos = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 11));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
*/
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.setPidPos = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.clearPidPos = function() {
  return this.setPidPos(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.hasPidPos = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional google.protobuf.DoubleValue tachometer = 12;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.getTachometer = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 12));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
*/
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.setTachometer = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.clearTachometer = function() {
  return this.setTachometer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.hasTachometer = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional google.protobuf.DoubleValue input_voltage = 13;
 * @return {?proto.google.protobuf.DoubleValue}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.getInputVoltage = function() {
  return /** @type{?proto.google.protobuf.DoubleValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.DoubleValue, 13));
};


/**
 * @param {?proto.google.protobuf.DoubleValue|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
*/
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.setInputVoltage = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.MotorControllerState} returns this
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.clearInputVoltage = function() {
  return this.setInputVoltage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.MotorControllerState.prototype.hasInputVoltage = function() {
  return jspb.Message.getField(this, 13) != null;
};


goog.object.extend(exports, proto.farm_ng_proto.tractor.v1);
