// source: farm_ng_proto/tractor/v1/rtk.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var farm_ng_proto_tractor_v1_geometry_pb = require('../../../farm_ng_proto/tractor/v1/geometry_pb.js');
goog.object.extend(proto, farm_ng_proto_tractor_v1_geometry_pb);
goog.exportSymbol('proto.farm_ng_proto.tractor.v1.RtkServiceStatus', null, global);
goog.exportSymbol('proto.farm_ng_proto.tractor.v1.RtkSolution', null, global);
goog.exportSymbol('proto.farm_ng_proto.tractor.v1.RtkSolution.Status', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.farm_ng_proto.tractor.v1.RtkSolution = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.farm_ng_proto.tractor.v1.RtkSolution, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.farm_ng_proto.tractor.v1.RtkSolution.displayName = 'proto.farm_ng_proto.tractor.v1.RtkSolution';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.farm_ng_proto.tractor.v1.RtkServiceStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.farm_ng_proto.tractor.v1.RtkServiceStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.farm_ng_proto.tractor.v1.RtkServiceStatus.displayName = 'proto.farm_ng_proto.tractor.v1.RtkServiceStatus';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.toObject = function(opt_includeInstance) {
  return proto.farm_ng_proto.tractor.v1.RtkSolution.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.farm_ng_proto.tractor.v1.RtkSolution} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.toObject = function(includeInstance, msg) {
  var f, obj = {
    stampGps: (f = msg.getStampGps()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    enuBaselineM: (f = msg.getEnuBaselineM()) && farm_ng_proto_tractor_v1_geometry_pb.Vec3.toObject(includeInstance, f),
    status: jspb.Message.getFieldWithDefault(msg, 5, 0),
    nSatelites: jspb.Message.getFieldWithDefault(msg, 6, 0),
    stdEnu: (f = msg.getStdEnu()) && farm_ng_proto_tractor_v1_geometry_pb.Vec3.toObject(includeInstance, f),
    stdEnNuUe: (f = msg.getStdEnNuUe()) && farm_ng_proto_tractor_v1_geometry_pb.Vec3.toObject(includeInstance, f),
    age: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    arRatio: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0),
    velocityEnuMs: (f = msg.getVelocityEnuMs()) && farm_ng_proto_tractor_v1_geometry_pb.Vec3.toObject(includeInstance, f),
    stdVelocityEnu: (f = msg.getStdVelocityEnu()) && farm_ng_proto_tractor_v1_geometry_pb.Vec3.toObject(includeInstance, f),
    stdVelocityEnNuUe: (f = msg.getStdVelocityEnNuUe()) && farm_ng_proto_tractor_v1_geometry_pb.Vec3.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.farm_ng_proto.tractor.v1.RtkSolution;
  return proto.farm_ng_proto.tractor.v1.RtkSolution.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.farm_ng_proto.tractor.v1.RtkSolution} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStampGps(value);
      break;
    case 2:
      var value = new farm_ng_proto_tractor_v1_geometry_pb.Vec3;
      reader.readMessage(value,farm_ng_proto_tractor_v1_geometry_pb.Vec3.deserializeBinaryFromReader);
      msg.setEnuBaselineM(value);
      break;
    case 5:
      var value = /** @type {!proto.farm_ng_proto.tractor.v1.RtkSolution.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNSatelites(value);
      break;
    case 7:
      var value = new farm_ng_proto_tractor_v1_geometry_pb.Vec3;
      reader.readMessage(value,farm_ng_proto_tractor_v1_geometry_pb.Vec3.deserializeBinaryFromReader);
      msg.setStdEnu(value);
      break;
    case 8:
      var value = new farm_ng_proto_tractor_v1_geometry_pb.Vec3;
      reader.readMessage(value,farm_ng_proto_tractor_v1_geometry_pb.Vec3.deserializeBinaryFromReader);
      msg.setStdEnNuUe(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAge(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setArRatio(value);
      break;
    case 11:
      var value = new farm_ng_proto_tractor_v1_geometry_pb.Vec3;
      reader.readMessage(value,farm_ng_proto_tractor_v1_geometry_pb.Vec3.deserializeBinaryFromReader);
      msg.setVelocityEnuMs(value);
      break;
    case 12:
      var value = new farm_ng_proto_tractor_v1_geometry_pb.Vec3;
      reader.readMessage(value,farm_ng_proto_tractor_v1_geometry_pb.Vec3.deserializeBinaryFromReader);
      msg.setStdVelocityEnu(value);
      break;
    case 13:
      var value = new farm_ng_proto_tractor_v1_geometry_pb.Vec3;
      reader.readMessage(value,farm_ng_proto_tractor_v1_geometry_pb.Vec3.deserializeBinaryFromReader);
      msg.setStdVelocityEnNuUe(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.farm_ng_proto.tractor.v1.RtkSolution.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.farm_ng_proto.tractor.v1.RtkSolution} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStampGps();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEnuBaselineM();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      farm_ng_proto_tractor_v1_geometry_pb.Vec3.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getNSatelites();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getStdEnu();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      farm_ng_proto_tractor_v1_geometry_pb.Vec3.serializeBinaryToWriter
    );
  }
  f = message.getStdEnNuUe();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      farm_ng_proto_tractor_v1_geometry_pb.Vec3.serializeBinaryToWriter
    );
  }
  f = message.getAge();
  if (f !== 0.0) {
    writer.writeFloat(
      9,
      f
    );
  }
  f = message.getArRatio();
  if (f !== 0.0) {
    writer.writeFloat(
      10,
      f
    );
  }
  f = message.getVelocityEnuMs();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      farm_ng_proto_tractor_v1_geometry_pb.Vec3.serializeBinaryToWriter
    );
  }
  f = message.getStdVelocityEnu();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      farm_ng_proto_tractor_v1_geometry_pb.Vec3.serializeBinaryToWriter
    );
  }
  f = message.getStdVelocityEnNuUe();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      farm_ng_proto_tractor_v1_geometry_pb.Vec3.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.Status = {
  STATUS_UNSPECIFIED: 0,
  STATUS_FIX: 1,
  STATUS_FLOAT: 2,
  STATUS_SBAS: 3,
  STATUS_DGPS: 4,
  STATUS_SINGLE: 5,
  STATUS_PPP: 6
};

/**
 * optional google.protobuf.Timestamp stamp_gps = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.getStampGps = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
*/
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.setStampGps = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.clearStampGps = function() {
  return this.setStampGps(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.hasStampGps = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Vec3 enu_baseline_m = 2;
 * @return {?proto.farm_ng_proto.tractor.v1.Vec3}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.getEnuBaselineM = function() {
  return /** @type{?proto.farm_ng_proto.tractor.v1.Vec3} */ (
    jspb.Message.getWrapperField(this, farm_ng_proto_tractor_v1_geometry_pb.Vec3, 2));
};


/**
 * @param {?proto.farm_ng_proto.tractor.v1.Vec3|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
*/
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.setEnuBaselineM = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.clearEnuBaselineM = function() {
  return this.setEnuBaselineM(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.hasEnuBaselineM = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Status status = 5;
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution.Status}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.getStatus = function() {
  return /** @type {!proto.farm_ng_proto.tractor.v1.RtkSolution.Status} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.farm_ng_proto.tractor.v1.RtkSolution.Status} value
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional int32 n_satelites = 6;
 * @return {number}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.getNSatelites = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.setNSatelites = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional Vec3 std_enu = 7;
 * @return {?proto.farm_ng_proto.tractor.v1.Vec3}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.getStdEnu = function() {
  return /** @type{?proto.farm_ng_proto.tractor.v1.Vec3} */ (
    jspb.Message.getWrapperField(this, farm_ng_proto_tractor_v1_geometry_pb.Vec3, 7));
};


/**
 * @param {?proto.farm_ng_proto.tractor.v1.Vec3|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
*/
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.setStdEnu = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.clearStdEnu = function() {
  return this.setStdEnu(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.hasStdEnu = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Vec3 std_en_nu_ue = 8;
 * @return {?proto.farm_ng_proto.tractor.v1.Vec3}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.getStdEnNuUe = function() {
  return /** @type{?proto.farm_ng_proto.tractor.v1.Vec3} */ (
    jspb.Message.getWrapperField(this, farm_ng_proto_tractor_v1_geometry_pb.Vec3, 8));
};


/**
 * @param {?proto.farm_ng_proto.tractor.v1.Vec3|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
*/
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.setStdEnNuUe = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.clearStdEnNuUe = function() {
  return this.setStdEnNuUe(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.hasStdEnNuUe = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional float age = 9;
 * @return {number}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.getAge = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.setAge = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional float ar_ratio = 10;
 * @return {number}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.getArRatio = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.setArRatio = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};


/**
 * optional Vec3 velocity_enu_ms = 11;
 * @return {?proto.farm_ng_proto.tractor.v1.Vec3}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.getVelocityEnuMs = function() {
  return /** @type{?proto.farm_ng_proto.tractor.v1.Vec3} */ (
    jspb.Message.getWrapperField(this, farm_ng_proto_tractor_v1_geometry_pb.Vec3, 11));
};


/**
 * @param {?proto.farm_ng_proto.tractor.v1.Vec3|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
*/
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.setVelocityEnuMs = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.clearVelocityEnuMs = function() {
  return this.setVelocityEnuMs(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.hasVelocityEnuMs = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional Vec3 std_velocity_enu = 12;
 * @return {?proto.farm_ng_proto.tractor.v1.Vec3}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.getStdVelocityEnu = function() {
  return /** @type{?proto.farm_ng_proto.tractor.v1.Vec3} */ (
    jspb.Message.getWrapperField(this, farm_ng_proto_tractor_v1_geometry_pb.Vec3, 12));
};


/**
 * @param {?proto.farm_ng_proto.tractor.v1.Vec3|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
*/
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.setStdVelocityEnu = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.clearStdVelocityEnu = function() {
  return this.setStdVelocityEnu(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.hasStdVelocityEnu = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional Vec3 std_velocity_en_nu_ue = 13;
 * @return {?proto.farm_ng_proto.tractor.v1.Vec3}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.getStdVelocityEnNuUe = function() {
  return /** @type{?proto.farm_ng_proto.tractor.v1.Vec3} */ (
    jspb.Message.getWrapperField(this, farm_ng_proto_tractor_v1_geometry_pb.Vec3, 13));
};


/**
 * @param {?proto.farm_ng_proto.tractor.v1.Vec3|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
*/
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.setStdVelocityEnNuUe = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.RtkSolution} returns this
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.clearStdVelocityEnNuUe = function() {
  return this.setStdVelocityEnNuUe(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.RtkSolution.prototype.hasStdVelocityEnNuUe = function() {
  return jspb.Message.getField(this, 13) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.farm_ng_proto.tractor.v1.RtkServiceStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.farm_ng_proto.tractor.v1.RtkServiceStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.farm_ng_proto.tractor.v1.RtkServiceStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.farm_ng_proto.tractor.v1.RtkServiceStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.farm_ng_proto.tractor.v1.RtkServiceStatus}
 */
proto.farm_ng_proto.tractor.v1.RtkServiceStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.farm_ng_proto.tractor.v1.RtkServiceStatus;
  return proto.farm_ng_proto.tractor.v1.RtkServiceStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.farm_ng_proto.tractor.v1.RtkServiceStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.farm_ng_proto.tractor.v1.RtkServiceStatus}
 */
proto.farm_ng_proto.tractor.v1.RtkServiceStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.farm_ng_proto.tractor.v1.RtkServiceStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.farm_ng_proto.tractor.v1.RtkServiceStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.farm_ng_proto.tractor.v1.RtkServiceStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.farm_ng_proto.tractor.v1.RtkServiceStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.farm_ng_proto.tractor.v1.RtkServiceStatus.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.farm_ng_proto.tractor.v1.RtkServiceStatus} returns this
 */
proto.farm_ng_proto.tractor.v1.RtkServiceStatus.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.farm_ng_proto.tractor.v1);
