// source: farm_ng_proto/tractor/v1/tracking_camera.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var farm_ng_proto_tractor_v1_geometry_pb = require('../../../farm_ng_proto/tractor/v1/geometry_pb.js');
goog.object.extend(proto, farm_ng_proto_tractor_v1_geometry_pb);
goog.exportSymbol('proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame', null, global);
goog.exportSymbol('proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.MotionType', null, global);
goog.exportSymbol('proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame', null, global);
goog.exportSymbol('proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.Confidence', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.displayName = 'proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.displayName = 'proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.toObject = function(opt_includeInstance) {
  return proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.toObject = function(includeInstance, msg) {
  var f, obj = {
    frameNumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
    stampPose: (f = msg.getStampPose()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    startPoseCurrent: (f = msg.getStartPoseCurrent()) && farm_ng_proto_tractor_v1_geometry_pb.SE3Pose.toObject(includeInstance, f),
    velocity: (f = msg.getVelocity()) && farm_ng_proto_tractor_v1_geometry_pb.Vec3.toObject(includeInstance, f),
    acceleration: (f = msg.getAcceleration()) && farm_ng_proto_tractor_v1_geometry_pb.Vec3.toObject(includeInstance, f),
    angularVelocity: (f = msg.getAngularVelocity()) && farm_ng_proto_tractor_v1_geometry_pb.Vec3.toObject(includeInstance, f),
    angularAcceleration: (f = msg.getAngularAcceleration()) && farm_ng_proto_tractor_v1_geometry_pb.Vec3.toObject(includeInstance, f),
    trackerConfidence: jspb.Message.getFieldWithDefault(msg, 8, 0),
    mapperConfidence: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame;
  return proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFrameNumber(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStampPose(value);
      break;
    case 3:
      var value = new farm_ng_proto_tractor_v1_geometry_pb.SE3Pose;
      reader.readMessage(value,farm_ng_proto_tractor_v1_geometry_pb.SE3Pose.deserializeBinaryFromReader);
      msg.setStartPoseCurrent(value);
      break;
    case 4:
      var value = new farm_ng_proto_tractor_v1_geometry_pb.Vec3;
      reader.readMessage(value,farm_ng_proto_tractor_v1_geometry_pb.Vec3.deserializeBinaryFromReader);
      msg.setVelocity(value);
      break;
    case 5:
      var value = new farm_ng_proto_tractor_v1_geometry_pb.Vec3;
      reader.readMessage(value,farm_ng_proto_tractor_v1_geometry_pb.Vec3.deserializeBinaryFromReader);
      msg.setAcceleration(value);
      break;
    case 6:
      var value = new farm_ng_proto_tractor_v1_geometry_pb.Vec3;
      reader.readMessage(value,farm_ng_proto_tractor_v1_geometry_pb.Vec3.deserializeBinaryFromReader);
      msg.setAngularVelocity(value);
      break;
    case 7:
      var value = new farm_ng_proto_tractor_v1_geometry_pb.Vec3;
      reader.readMessage(value,farm_ng_proto_tractor_v1_geometry_pb.Vec3.deserializeBinaryFromReader);
      msg.setAngularAcceleration(value);
      break;
    case 8:
      var value = /** @type {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.Confidence} */ (reader.readEnum());
      msg.setTrackerConfidence(value);
      break;
    case 9:
      var value = /** @type {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.Confidence} */ (reader.readEnum());
      msg.setMapperConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFrameNumber();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getStampPose();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getStartPoseCurrent();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      farm_ng_proto_tractor_v1_geometry_pb.SE3Pose.serializeBinaryToWriter
    );
  }
  f = message.getVelocity();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      farm_ng_proto_tractor_v1_geometry_pb.Vec3.serializeBinaryToWriter
    );
  }
  f = message.getAcceleration();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      farm_ng_proto_tractor_v1_geometry_pb.Vec3.serializeBinaryToWriter
    );
  }
  f = message.getAngularVelocity();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      farm_ng_proto_tractor_v1_geometry_pb.Vec3.serializeBinaryToWriter
    );
  }
  f = message.getAngularAcceleration();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      farm_ng_proto_tractor_v1_geometry_pb.Vec3.serializeBinaryToWriter
    );
  }
  f = message.getTrackerConfidence();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getMapperConfidence();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.Confidence = {
  CONFIDENCE_UNSPECIFIED: 0,
  CONFIDENCE_FAILED: 1,
  CONFIDENCE_LOW: 2,
  CONFIDENCE_MEDIUM: 3,
  CONFIDENCE_HIGH: 4
};

/**
 * optional int32 frame_number = 1;
 * @return {number}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.getFrameNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.setFrameNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp stamp_pose = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.getStampPose = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
*/
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.setStampPose = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.clearStampPose = function() {
  return this.setStampPose(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.hasStampPose = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional SE3Pose start_pose_current = 3;
 * @return {?proto.farm_ng_proto.tractor.v1.SE3Pose}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.getStartPoseCurrent = function() {
  return /** @type{?proto.farm_ng_proto.tractor.v1.SE3Pose} */ (
    jspb.Message.getWrapperField(this, farm_ng_proto_tractor_v1_geometry_pb.SE3Pose, 3));
};


/**
 * @param {?proto.farm_ng_proto.tractor.v1.SE3Pose|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
*/
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.setStartPoseCurrent = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.clearStartPoseCurrent = function() {
  return this.setStartPoseCurrent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.hasStartPoseCurrent = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Vec3 velocity = 4;
 * @return {?proto.farm_ng_proto.tractor.v1.Vec3}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.getVelocity = function() {
  return /** @type{?proto.farm_ng_proto.tractor.v1.Vec3} */ (
    jspb.Message.getWrapperField(this, farm_ng_proto_tractor_v1_geometry_pb.Vec3, 4));
};


/**
 * @param {?proto.farm_ng_proto.tractor.v1.Vec3|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
*/
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.setVelocity = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.clearVelocity = function() {
  return this.setVelocity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.hasVelocity = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Vec3 acceleration = 5;
 * @return {?proto.farm_ng_proto.tractor.v1.Vec3}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.getAcceleration = function() {
  return /** @type{?proto.farm_ng_proto.tractor.v1.Vec3} */ (
    jspb.Message.getWrapperField(this, farm_ng_proto_tractor_v1_geometry_pb.Vec3, 5));
};


/**
 * @param {?proto.farm_ng_proto.tractor.v1.Vec3|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
*/
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.setAcceleration = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.clearAcceleration = function() {
  return this.setAcceleration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.hasAcceleration = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional Vec3 angular_velocity = 6;
 * @return {?proto.farm_ng_proto.tractor.v1.Vec3}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.getAngularVelocity = function() {
  return /** @type{?proto.farm_ng_proto.tractor.v1.Vec3} */ (
    jspb.Message.getWrapperField(this, farm_ng_proto_tractor_v1_geometry_pb.Vec3, 6));
};


/**
 * @param {?proto.farm_ng_proto.tractor.v1.Vec3|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
*/
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.setAngularVelocity = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.clearAngularVelocity = function() {
  return this.setAngularVelocity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.hasAngularVelocity = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional Vec3 angular_acceleration = 7;
 * @return {?proto.farm_ng_proto.tractor.v1.Vec3}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.getAngularAcceleration = function() {
  return /** @type{?proto.farm_ng_proto.tractor.v1.Vec3} */ (
    jspb.Message.getWrapperField(this, farm_ng_proto_tractor_v1_geometry_pb.Vec3, 7));
};


/**
 * @param {?proto.farm_ng_proto.tractor.v1.Vec3|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
*/
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.setAngularAcceleration = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.clearAngularAcceleration = function() {
  return this.setAngularAcceleration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.hasAngularAcceleration = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Confidence tracker_confidence = 8;
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.Confidence}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.getTrackerConfidence = function() {
  return /** @type {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.Confidence} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.Confidence} value
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.setTrackerConfidence = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional Confidence mapper_confidence = 9;
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.Confidence}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.getMapperConfidence = function() {
  return /** @type {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.Confidence} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.Confidence} value
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame} returns this
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraPoseFrame.prototype.setMapperConfidence = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.prototype.toObject = function(opt_includeInstance) {
  return proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.toObject = function(includeInstance, msg) {
  var f, obj = {
    frameNumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
    stampMotion: (f = msg.getStampMotion()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    motionType: jspb.Message.getFieldWithDefault(msg, 3, 0),
    motionData: (f = msg.getMotionData()) && farm_ng_proto_tractor_v1_geometry_pb.Vec3.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame;
  return proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFrameNumber(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStampMotion(value);
      break;
    case 3:
      var value = /** @type {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.MotionType} */ (reader.readEnum());
      msg.setMotionType(value);
      break;
    case 4:
      var value = new farm_ng_proto_tractor_v1_geometry_pb.Vec3;
      reader.readMessage(value,farm_ng_proto_tractor_v1_geometry_pb.Vec3.deserializeBinaryFromReader);
      msg.setMotionData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFrameNumber();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getStampMotion();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getMotionType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getMotionData();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      farm_ng_proto_tractor_v1_geometry_pb.Vec3.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.MotionType = {
  MOTION_TYPE_UNSPECIFIED: 0,
  MOTION_TYPE_GYRO: 1,
  MOTION_TYPE_ACCEL: 2
};

/**
 * optional int32 frame_number = 1;
 * @return {number}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.prototype.getFrameNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame} returns this
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.prototype.setFrameNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp stamp_motion = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.prototype.getStampMotion = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame} returns this
*/
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.prototype.setStampMotion = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame} returns this
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.prototype.clearStampMotion = function() {
  return this.setStampMotion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.prototype.hasStampMotion = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional MotionType motion_type = 3;
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.MotionType}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.prototype.getMotionType = function() {
  return /** @type {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.MotionType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.MotionType} value
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame} returns this
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.prototype.setMotionType = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional Vec3 motion_data = 4;
 * @return {?proto.farm_ng_proto.tractor.v1.Vec3}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.prototype.getMotionData = function() {
  return /** @type{?proto.farm_ng_proto.tractor.v1.Vec3} */ (
    jspb.Message.getWrapperField(this, farm_ng_proto_tractor_v1_geometry_pb.Vec3, 4));
};


/**
 * @param {?proto.farm_ng_proto.tractor.v1.Vec3|undefined} value
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame} returns this
*/
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.prototype.setMotionData = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame} returns this
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.prototype.clearMotionData = function() {
  return this.setMotionData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.farm_ng_proto.tractor.v1.TrackingCameraMotionFrame.prototype.hasMotionData = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.farm_ng_proto.tractor.v1);
